# Data Loading, Storage

In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [ ]:
# You have to upload the data by using the Files function on your dashboard

## Reading and Writing Data in Text Format

two methods:
- *read_csv*: Read a comma-separated values (csv) file into DataFrame. Also supports optionally iterating or breaking of the file into chunks.
- *to_csv*: Write object to a comma-separated values (csv) file.

### Reading Text Files

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
path = "/content/drive/MyDrive/Colab_Notebooks/data/ex1.csv"
df = pd.read_csv(path)
df

Empty DataFrame
Columns: [Hello Google Drive!]
Index: []

In [16]:
type(df)

pandas.core.frame.DataFrame

In [24]:
 !cat "/content/drive/MyDrive/Colab_Notebooks/data/ex1.csv"
 #!cat "examples/ex1.csv"

Hello Google Drive!

define separator value and header

In [25]:
# define the table sepator value

df = pd.read_csv(path, sep='\t')
df

Empty DataFrame
Columns: [Hello Google Drive!]
Index: []

In [26]:
# define if the table header exists 

df = pd.read_csv(path, header=None)
df

                     0
0  Hello Google Drive!

In [27]:
path = "/content/drive/MyDrive/Colab_Notebooks/data/Copia di ex2.csv"

In [ ]:
 !cat "ex2.csv"

In [28]:
pd.read_csv(path, sep=',', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

define column name and/or index name

In [ ]:
# define column name

pd.read_csv('ex2.csv', names=['a', 'b', 'c', 'd', 'message'])

In [ ]:
# define index name

names = ['a', 'b', 'c', 'd', 'message']
pd.read_csv('ex2.csv', names=names, index_col='message')

you can skip a list of row

In [ ]:
!cat "ex4.csv"

In [ ]:
pd.read_csv('ex4.csv', sep=',')

In [ ]:
# you can skip a list of row
pd.read_csv('ex4.csv', skiprows=[0, 2, 3])

In [ ]:
!cat ex5.csv

In [ ]:
result = pd.read_csv('ex5.csv')
result

In [ ]:
None; np.nan

In [ ]:
pd.isnull(result)

define *na_values*

In [ ]:
result = pd.read_csv('ex5.csv', na_values=['NULL', 'one'])
result

In [ ]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
pd.read_csv('ex5.csv', na_values=sentinels)
#pd.read_csv('examples/ex5.csv', na_values=sentinels)

### Reading Text Files in Pieces

In [ ]:
result = pd.read_csv('ex6.csv')
result

Read only a fixed number of rows

In [ ]:
pd.read_csv('ex6.csv', nrows=5)

Read Text Files in chunks

In [ ]:
chunker = pd.read_csv('ex6.csv', chunksize=1000)
chunker

In [ ]:
chunk = next(chunker)
chunk.head(5)

In [ ]:
for chunk in chunker:
  print("chunk size: {}".format(chunk.shape))
  break

In [ ]:
# tot = pd.Series([], dtype=float)
# for piece in chunker:
#     tot = tot.add(piece['key'].value_counts(), fill_value=0)

# tot = tot.sort_values(ascending=False)

### Writing Data to Text Format

In [ ]:
data = pd.read_csv('ex5.csv')
data

In [ ]:
data.iloc[0,0] = 999

In [ ]:
data

In [ ]:
data.to_csv('out.csv',index=True)

In [ ]:
pd.read_csv('out.csv', sep=',')

In [ ]:
!cat out.csv

In [ ]:
data.to_csv('out.csv', index=False, sep=';')

In [ ]:
pd.read_csv('out.csv', sep=';')

In [ ]:
!cat out.csv

### Reading and Writing Microsoft Excel Files

Read option 1: Using *ExcelFile* class

In [ ]:
#xlsx = pd.ExcelFile('examples/ex1.xlsx')
xlsx = pd.ExcelFile('ex1.xlsx')

In [ ]:
xlsx

In [ ]:
pd.read_excel(xlsx, 'Sheet1')

Read option 2: Using *read_excel* method

In [ ]:
frame = pd.read_excel('ex1.xlsx', 'Sheet1')
frame

Write option 1: using *ExcelWriter* object

In [ ]:
writer = pd.ExcelWriter('ex2.xlsx')
frame.to_excel(writer, 'Sheet1')
writer.save()

Write option 2: using *to_excel* method

In [ ]:
frame

In [ ]:
frame.to_excel('ex2_out.xlsx')

In [ ]:
!rm examples/ex2.xlsx

### Working with Delimited Formats

In [ ]:
!cat ex7.csv

In [ ]:
import csv
f = open('ex7.csv')

reader = csv.reader(f)

In [ ]:
for line in reader:
    print(line)

In [ ]:
with open('ex7.csv') as f:
    lines = list(csv.reader(f))

In [ ]:
header, values = lines[0], lines[1:]

In [ ]:
values

In [ ]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

## Optional *Impossible* File

In [ ]:
with open('ex3.txt', 'r') as f:
  lines = f.readlines()
lines

In [ ]:
columns = [val.strip() for val in lines[0].split(' ') if val != '']
columns

In [ ]:
data = []
for row in lines[1:]:
  res = [val.strip() for val in row.split(' ') if val != '']
  data.append(res)

In [ ]:
data

In [ ]:
columns

In [ ]:
columns.insert(0, 'index')
columns

In [ ]:
ds = pd.DataFrame(data, columns=columns)
ds

In [ ]:
ds.set_index('index')